Layout/CommentIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
